import { useQuery } from '@tanstack/react-query';
import { elasticityApi } from '../utils/api';
import type { ScenariosResponse } from '../types';

/**
 * Hook to fetch restoration scenario data for the scenario explorer
 */
export function useScenarios(improvementPct: number = 10) {
  return useQuery({
    queryKey: ['elasticity', 'scenarios', improvementPct],
    queryFn: () => elasticityApi.getScenarios(improvementPct),
    staleTime: 30 * 60 * 1000, // 30 minutes - rarely changes
    retry: 2,
  });
}

// Default fallback data based on corrected transition matrix (Jan 2026)
export const DEFAULT_SCENARIOS_DATA: ScenariosResponse = {
  data: {
    individual: [
      {
        from_class: 'Large Adult (>2000 cm\u00B2)',
        to_class: 'Large Adult (>2000 cm\u00B2)',
        from_short: 'SC5',
        to_short: 'SC5',
        baseline_value: 0.863,
        perturbed_value: 0.950,
        baseline_lambda: 0.986,
        new_lambda: 1.027,
        delta_lambda: 0.061,
        pct_lambda_change: 6.28,
        elasticity_pct: 54.8,
        restoration_action: 'Reduce adult mortality through disease management and physical protection',
        transition_type: 'stasis',
        category: 'Survival',
      },
      {
        from_class: 'Small Adult (500-2000 cm\u00B2)',
        to_class: 'Small Adult (500-2000 cm\u00B2)',
        from_short: 'SC4',
        to_short: 'SC4',
        baseline_value: 0.575,
        perturbed_value: 0.633,
        baseline_lambda: 0.986,
        new_lambda: 0.978,
        delta_lambda: 0.012,
        pct_lambda_change: 1.27,
        elasticity_pct: 11.6,
        restoration_action: 'Protect small adults from predation and sedimentation',
        transition_type: 'stasis',
        category: 'Survival',
      },
      {
        from_class: 'Small Adult (500-2000 cm\u00B2)',
        to_class: 'Large Adult (>2000 cm\u00B2)',
        from_short: 'SC4',
        to_short: 'SC5',
        baseline_value: 0.156,
        perturbed_value: 0.171,
        baseline_lambda: 0.986,
        new_lambda: 0.973,
        delta_lambda: 0.006,
        pct_lambda_change: 0.66,
        elasticity_pct: 6.8,
        restoration_action: 'Enhance growth conditions for sub-adults to reach adult size',
        transition_type: 'growth',
        category: 'Growth',
      },
      {
        from_class: 'Large Juvenile (100-500 cm\u00B2)',
        to_class: 'Large Juvenile (100-500 cm\u00B2)',
        from_short: 'SC3',
        to_short: 'SC3',
        baseline_value: 0.493,
        perturbed_value: 0.542,
        baseline_lambda: 0.986,
        new_lambda: 0.972,
        delta_lambda: 0.006,
        pct_lambda_change: 0.65,
        elasticity_pct: 5.9,
        restoration_action: 'Protect juveniles from algal overgrowth and predation',
        transition_type: 'stasis',
        category: 'Survival',
      },
      {
        from_class: 'Large Juvenile (100-500 cm\u00B2)',
        to_class: 'Small Adult (500-2000 cm\u00B2)',
        from_short: 'SC3',
        to_short: 'SC4',
        baseline_value: 0.129,
        perturbed_value: 0.142,
        baseline_lambda: 0.986,
        new_lambda: 0.971,
        delta_lambda: 0.005,
        pct_lambda_change: 0.49,
        elasticity_pct: 4.9,
        restoration_action: 'Enhance growth from juvenile to adult size classes',
        transition_type: 'growth',
        category: 'Growth',
      },
      {
        from_class: 'Large Adult (>2000 cm\u00B2)',
        to_class: 'Large Juvenile (100-500 cm\u00B2)',
        from_short: 'SC5',
        to_short: 'SC3',
        baseline_value: 0.295,
        perturbed_value: 0.324,
        baseline_lambda: 0.986,
        new_lambda: 0.967,
        delta_lambda: 0.001,
        pct_lambda_change: 0.10,
        elasticity_pct: 2.9,
        restoration_action: 'Retrogression from SC5 to SC3 (partial mortality)',
        transition_type: 'shrinkage',
        category: 'Retrogression',
      },
      {
        from_class: 'Small Juvenile (25-100 cm\u00B2)',
        to_class: 'Large Juvenile (100-500 cm\u00B2)',
        from_short: 'SC2',
        to_short: 'SC3',
        baseline_value: 0.282,
        perturbed_value: 0.310,
        baseline_lambda: 0.986,
        new_lambda: 0.968,
        delta_lambda: 0.002,
        pct_lambda_change: 0.18,
        elasticity_pct: 1.8,
        restoration_action: 'Improve juvenile growth by reducing competition',
        transition_type: 'growth',
        category: 'Growth',
      },
      {
        from_class: 'Recruit (0-25 cm\u00B2)',
        to_class: 'Recruit (0-25 cm\u00B2)',
        from_short: 'SC1',
        to_short: 'SC1',
        baseline_value: 0.246,
        perturbed_value: 0.270,
        baseline_lambda: 0.986,
        new_lambda: 0.967,
        delta_lambda: 0.000,
        pct_lambda_change: 0.04,
        elasticity_pct: 0.4,
        restoration_action: 'Improve recruit survival through substrate preparation',
        transition_type: 'stasis',
        category: 'Survival',
      },
    ],
    combined: [
      {
        scenario_id: 'protect_adults',
        scenario_name: 'Protect Adults',
        description: 'Improve SC4 and SC5 stasis (survival) by reducing disease and physical damage',
        transitions_affected: ['SC5\u2192SC5', 'SC4\u2192SC4'],
        baseline_lambda: 0.986,
        new_lambda: 1.036,
        delta_lambda: 0.070,
        pct_lambda_change: 7.20,
        achieves_stability: true,
      },
      {
        scenario_id: 'enhance_growth',
        scenario_name: 'Enhance Growth',
        description: 'Improve all growth transitions by improving water quality and reducing competition',
        transitions_affected: ['SC2\u2192SC3', 'SC3\u2192SC4', 'SC4\u2192SC5'],
        baseline_lambda: 0.986,
        new_lambda: 0.981,
        delta_lambda: 0.014,
        pct_lambda_change: 1.49,
        achieves_stability: false,
      },
      {
        scenario_id: 'outplanting',
        scenario_name: 'Outplanting',
        description: 'Increase early life stage survival and growth (SC1, SC2)',
        transitions_affected: ['SC1\u2192SC1', 'SC1\u2192SC2', 'SC2\u2192SC2'],
        baseline_lambda: 0.986,
        new_lambda: 0.968,
        delta_lambda: 0.002,
        pct_lambda_change: 0.21,
        achieves_stability: false,
      },
      {
        scenario_id: 'reduce_shrinkage',
        scenario_name: 'Reduce Shrinkage',
        description: 'Reduce partial mortality that causes colonies to shrink to smaller size classes',
        transitions_affected: ['SC5\u2192SC4', 'SC4\u2192SC3', 'SC5\u2192SC3'],
        baseline_lambda: 0.986,
        new_lambda: 0.957,
        delta_lambda: -0.009,
        pct_lambda_change: -0.90,
        achieves_stability: false,
      },
      {
        scenario_id: 'full_restoration',
        scenario_name: 'Full Restoration',
        description: 'Combine all interventions: protect adults, enhance growth, and reduce shrinkage',
        transitions_affected: ['SC5\u2192SC5', 'SC4\u2192SC4', 'SC3\u2192SC4', 'SC4\u2192SC5'],
        baseline_lambda: 0.986,
        new_lambda: 1.045,
        delta_lambda: 0.079,
        pct_lambda_change: 8.18,
        achieves_stability: true,
      },
    ],
    path_to_stability: [
      {
        scenario_id: 'protect_adults',
        scenario_name: 'Protect Adults',
        improvement_needed_pct: 5.0,
        feasibility: 'feasible',
        note: 'Reducing adult mortality by ~5% could stabilize the population',
      },
      {
        scenario_id: 'enhance_growth',
        scenario_name: 'Enhance Growth',
        improvement_needed_pct: 23.1,
        feasibility: 'moderate',
        note: 'Growth improvements alone require substantial changes to reach stability',
      },
      {
        scenario_id: 'outplanting',
        scenario_name: 'Outplanting',
        improvement_needed_pct: 84.2,
        feasibility: 'difficult',
        note: 'Reproduction alone cannot feasibly compensate for the population decline',
      },
      {
        scenario_id: 'reduce_shrinkage',
        scenario_name: 'Reduce Shrinkage',
        improvement_needed_pct: 200.0,
        feasibility: 'difficult',
        note: 'Cannot achieve stability through shrinkage reduction alone',
      },
      {
        scenario_id: 'full_restoration',
        scenario_name: 'Full Restoration',
        improvement_needed_pct: 4.3,
        feasibility: 'feasible',
        note: 'Combined interventions need only ~4% improvement each to achieve growth',
      },
    ],
  },
  meta: {
    improvement_pct: 10,
    baseline_lambda: 0.986,
    target_lambda: 1.0,
    note: 'Fallback data - API unavailable',
  },
};
